### ISSUE TITLE
plonesite recipe broken with 5.1.5

### ISSUE THREAD

**Issue by pbauer** [collective/demo.plone.de#35]
I tested using Plone 5.1.5 with https://github.com/collective/demo.plone.de/commit/cf67c09087c44db2a76520fb6a93d25f35037d3d and found that the recipe did not work anymore.

```
Installing plonesite.
.
daemon process started, pid=20140
Traceback (most recent call last):
  File "/home/zope/demo.plone.de/parts/zeoclient1/bin/interpreter", line 106, in <module>
    exec(_val)
  File "<string>", line 1, in <module>
ImportError: No module named globalrequest
.
daemon process stopped
Installing supervisor-crontab.
```

It needs investigating what is responsible.

**Comment by pbauer** [comment]
Fixed with https://github.com/starzel/buildout/issues/43
